language: objective-c

compiler:
 - clang

env:
 - CONFIGURATION=Dev
 - CONFIGURATION=Release

before_install:
 - brew install boost protobuf osm-pbf expat google-sparsehash geos gdal

install:
 - cd ..
 - git clone https://github.com/osmcode/osm-testdata.git
 - cd ../

before_script:
 - true

script:
 - mkdir build
 - cd build
 - export BREW_PREFIX=$(brew --prefix)
 - cmake ../ -LA -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DBUILD_EXAMPLES=ON -DBUILD_DATA_TESTS=ON -DBUILD_BENCHMARKS=ON -DBOOST_ROOT="${BREW_PREFIX}" -DCMAKE_INCLUDE_PATH="${BREW_PREFIX}/include" -DCMAKE_LIBRARY_PATH="${BREW_PREFIX}/lib" \
 - make VERBOSE=1

